# Halve the number of channels for backbone
save_dir: workspace/nanodet_g_manual_head_half
model:
  arch:
    name: GFL
    backbone:
      name: CustomCspNet
      net_cfg: [[ 'Conv', 3, 16, 3, 2],  # 1/2
                [ 'MaxPool', 3, 2 ],  # 1/4
                [ 'CspBlock', 16, 1, 3, 1 ],  # 1/4
                [ 'CspBlock', 32, 2, 3, 2 ],  # 1/8
                [ 'CspBlock', 64, 2, 3, 2 ],  # 1/16
                [ 'CspBlock', 128, 3, 3, 2 ]]  # 1/32
      out_stages: [3,4,5]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [64, 128, 256]
      out_channels: 64
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
  ......
